name: "A Python Container Action Template"
description: "Get started with Python Container action"
author: "yanglbme"
branding:
  icon: 'copy'
  color: 'gray-dark'
inputs:
  username:
    description: "Username"
    required: true
  age:
    description: "Age"
    required: false
    default: '18'
outputs:
  res:
    description: "Result from the action"
  time:
    description: "Running time"
runs:
  using: "docker"
  image: "Dockerfile"