name: My Workflow
on: [ push, pull_request, workflow_dispatch ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run action
        uses: actions/checkout@v2

      - name: Run container action
        uses: actionv/python-container-action@main
        with:
          username: yanglbme

      - name: Check outputs
        run: echo "The result is ${{ steps.myaction.outputs.res }}"
